pull_request_rules:
  - name: Merge queue
    conditions:
      - label=automerge
      - status-success=ci
      - "#approved-reviews-by>=1"
      - "head~=^(?!main$).*"  # Not targeting main directly
    actions:
      queue:
        name: default
        method: rebase
        
  - name: Auto-approve dependency updates
    conditions:
      - author~=^(dependabot\[bot\]|renovate\[bot\])$
      - status-success=ci
    actions:
      review:
        type: APPROVE
      label:
        add: ["automerge"]
        
  - name: Auto-rebase on conflict
    conditions:
      - conflict
    actions:
      rebase: