[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "testgen_copilot"
version = "0.0.1"
requires-python = ">=3.8"
description = "CLI tool and VS Code extension that uses LLMs to automatically generate comprehensive unit tests and highlight potential security vulnerabilities"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0"
]

[project.scripts]
testgen = "testgen_copilot.cli:main"
testgen-autonomous = "testgen_copilot.autonomous_manager:main"
testgen-metrics = "testgen_copilot.metrics_collector:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["testgen_copilot"]
