name: Bug Report
description: File a bug report to help us improve TestGen Copilot Assistant
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have updated to the latest version of TestGen Copilot Assistant
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. On file '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: TestGen Version
      description: What version of TestGen Copilot Assistant are you running?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
        - "3.8"
        - "Other (specify in additional info)"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - "Linux (Ubuntu/Debian)"
        - "Linux (RHEL/CentOS/Fedora)"
        - "Linux (Other)"
        - "macOS"
        - "Windows"
        - "Docker"
        - "Other (specify in additional info)"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - OS Version: 
        - Shell: 
        - Terminal: 
        - Virtual Environment: 
        - Container: 
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your TestGen configuration (remove any sensitive information)
      placeholder: |
        ```json
        {
          "language": "python",
          "test_framework": "pytest",
          "coverage_target": 80
        }
        ```
      render: json
    validations:
      required: false

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: The exact command you ran when the bug occurred
      placeholder: "testgen generate --file example.py --output tests/"
      render: bash
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Full error message or output (if any)
      placeholder: Paste the complete error output here
      render: text
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Relevant log output (run with --log-level debug for verbose output)
      placeholder: Paste relevant log output here
      render: text
    validations:
      required: false

  - type: textarea
    id: sample-code
    attributes:
      label: Sample Code
      description: Minimal code example that reproduces the issue (if applicable)
      placeholder: |
        ```python
        def example_function():
            # Your code here
            pass
        ```
      render: python
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: What is the impact of this bug?
      options:
        - label: Blocks core functionality
        - label: Causes incorrect results
        - label: Performance degradation
        - label: Minor inconvenience
        - label: Security concern

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this bug fix?
      options:
        - "Critical (system unusable)"
        - "High (major functionality broken)"
        - "Medium (functionality impaired)"
        - "Low (minor issue)"
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Any workaround you've found for this issue
      placeholder: Describe any temporary workaround you've discovered
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Add any other context about the problem here
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this bug?
      options:
        - label: I am willing to submit a pull request to fix this bug
        - label: I am willing to help test a fix
        - label: I can provide additional debugging information if needed