"""TestGen Copilot package."""

# from .autonomous_backlog import BacklogManager, BacklogItem, TaskType, TaskStatus, RiskTier
from .auto_scaling import (
    AutoScaler,
    LoadBalancer,
    ScalingDecision,
    ScalingMetrics,
    ScalingPolicy,
    WorkloadAnalyzer,
    WorkloadPattern,
    get_auto_scaler,
)
from .autonomous_execution import ExecutionPhase, ExecutionResult, SecurityChecker, TDDExecutor
from .cache import (
    CacheEntry,
    LRUCache,
    analysis_cache,
    ast_cache,
    cached_operation,
    clear_all_caches,
    file_content_cache,
    get_cache_stats,
)
from .compliance import (
    ComplianceEngine,
    ComplianceFramework,
    DataClassification,
    DataProcessingRecord,
    PrivacyControlsManager,
    ProcessingPurpose,
    RetentionPeriod,
    check_data_compliance,
    get_compliance_engine,
    log_data_processing,
)
from .core import identity
from .coverage import (
    CoverageAnalyzer,
    CoverageResult,
    ParallelCoverageAnalyzer,
    StreamingCoverageAnalyzer,
)
from .database import (
    AnalysisRepository,
    AnalysisResult,
    DatabaseConnection,
    MetricsRepository,
    ProcessingSession,
    ProjectMetrics,
    SecurityRepository,
    SessionRepository,
    TestCase,
    TestCaseRepository,
    get_database,
    run_migrations,
)
from .file_utils import FileSizeError, SyntaxErrorStrategy, safe_parse_ast, safe_read_file
from .generator import GenerationConfig, TestGenerator
from .integrations import (
    CICDIntegration,
    CloudStorageClient,
    GitHubClient,
    GitHubIntegration,
    JWTManager,
    NotificationService,
    OAuthHandler,
    WebhookManager,
)

# Global-first features (Generation 4)
from .internationalization import (
    LocaleInfo,
    LocalizationManager,
    SupportedLocales,
    format_localized_currency,
    format_localized_datetime,
    get_localization_manager,
    set_global_locale,
    t,
)

# from .autonomous_manager import AutonomousManager
from .metrics_collector import CIMetrics, DORAMetrics, MetricsCollector, OperationalMetrics

# Robustness and reliability components (Generation 2)
from .monitoring import (
    Alert,
    AlertSeverity,
    ApplicationMetrics,
    HealthMonitor,
    SystemMetrics,
    get_health_monitor,
    shutdown_monitoring,
)
from .multi_region import (
    DataLocation,
    DataResidencyRequirement,
    MultiRegionManager,
    Region,
    RegionConfig,
    ReplicationStrategy,
    get_multi_region_manager,
    get_optimal_region,
    store_data_globally,
)

# Optimization and scaling components (Generation 3)
from .performance_optimizer import (
    AdaptiveResourceManager,
    ConcurrentExecutor,
    PerformanceCache,
    PerformanceMetrics,
    PerformanceOptimizer,
    get_performance_optimizer,
)
from .quality import TestQualityScorer
from .quantum_planner import (
    QuantumAnnealer,
    QuantumTask,
    QuantumTaskPlanner,
    ResourceQuantum,
    TaskPriority,
    TaskState,
    create_quantum_planner,
    demo_quantum_planning,
)
from .resilience import (
    Bulkhead,
    BulkheadConfig,
    BulkheadFullError,
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitBreakerError,
    CircuitState,
    ResilienceManager,
    RetryConfig,
    RetryExhaustedError,
    RetryMechanism,
    RetryStrategy,
    bulkhead,
    circuit_breaker,
    get_resilience_manager,
    retry,
)
from .resource_limits import (
    AST_PARSE_TIMEOUT,
    MAX_PROJECT_FILES,
    BatchProcessor,
    CrossPlatformTimeoutHandler,
    MemoryMonitor,
    ResourceLimits,
    ResourceMemoryError,
    ResourceMonitor,
    TimeoutHandler,
    safe_parse_ast_with_timeout,
    validate_test_content,
)
from .security import SecurityIssue, SecurityReport, SecurityScanner
from .security_monitoring import (
    SecurityEvent,
    SecurityThreat,
    ThreatCategory,
    ThreatLevel,
    get_security_scanner,
)
from .security_monitoring import SecurityScanner as EnhancedSecurityScanner
from .security_rules import SecurityRule, SecurityRuleSet, SecurityRulesManager
from .streaming import (
    FileStreamProcessor,
    StreamingProcessor,
    StreamingProgress,
    create_progress_reporter,
)
from .version import __version__, get_package_version, get_version_info
from .vscode import scaffold_extension, suggest_from_diagnostics, write_usage_docs

__all__ = [
    "identity",
    "GenerationConfig",
    "TestGenerator",
    "SecurityScanner",
    "SecurityIssue",
    "SecurityReport",
    "SecurityRulesManager",
    "SecurityRule",
    "SecurityRuleSet",
    "scaffold_extension",
    "suggest_from_diagnostics",
    "write_usage_docs",
    "CoverageAnalyzer",
    "ParallelCoverageAnalyzer",
    "CoverageResult",
    "StreamingCoverageAnalyzer",
    "StreamingProcessor",
    "FileStreamProcessor",
    "StreamingProgress",
    "create_progress_reporter",
    "TestQualityScorer",
    "safe_read_file",
    "FileSizeError",
    "safe_parse_ast",
    "SyntaxErrorStrategy",
    "MemoryMonitor",
    "BatchProcessor",
    "TimeoutHandler",
    "CrossPlatformTimeoutHandler",
    "ResourceMemoryError",
    "safe_parse_ast_with_timeout",
    "validate_test_content",
    "AST_PARSE_TIMEOUT",
    "MAX_PROJECT_FILES",
    "ResourceLimits",
    "ResourceMonitor",
    "CircuitBreaker",
    "safe_parse_ast",
    "ASTParsingError",
    "extract_functions",
    "extract_classes",
    "LRUCache",
    "CacheEntry",
    "cached_operation",
    "get_cache_stats",
    "clear_all_caches",
    "ast_cache",
    "file_content_cache",
    "analysis_cache",
    "get_package_version",
    "get_version_info",
    "__version__",
    "BacklogManager",
    "BacklogItem",
    "TaskType",
    "TaskStatus",
    "RiskTier",
    "TDDExecutor",
    "SecurityChecker",
    "ExecutionResult",
    "ExecutionPhase",
    "AutonomousManager",
    "MetricsCollector",
    "DORAMetrics",
    "CIMetrics",
    "OperationalMetrics",
    "DatabaseConnection",
    "get_database",
    "AnalysisResult",
    "TestCase",
    "SecurityIssue",
    "ProjectMetrics",
    "ProcessingSession",
    "AnalysisRepository",
    "TestCaseRepository",
    "SecurityRepository",
    "MetricsRepository",
    "SessionRepository",
    "run_migrations",
    "GitHubClient",
    "GitHubIntegration",
    "NotificationService",
    "CICDIntegration",
    "OAuthHandler",
    "JWTManager",
    "CloudStorageClient",
    "WebhookManager",
    "QuantumTaskPlanner",
    "QuantumTask",
    "TaskPriority",
    "TaskState",
    "ResourceQuantum",
    "QuantumAnnealer",
    "create_quantum_planner",
    "demo_quantum_planning",
    # Robustness and reliability components
    "HealthMonitor",
    "SystemMetrics",
    "ApplicationMetrics",
    "Alert",
    "AlertSeverity",
    "get_health_monitor",
    "shutdown_monitoring",
    "CircuitBreaker",
    "RetryMechanism",
    "Bulkhead",
    "ResilienceManager",
    "CircuitBreakerConfig",
    "RetryConfig",
    "BulkheadConfig",
    "CircuitState",
    "RetryStrategy",
    "get_resilience_manager",
    "circuit_breaker",
    "retry",
    "bulkhead",
    "CircuitBreakerError",
    "RetryExhaustedError",
    "BulkheadFullError",
    "EnhancedSecurityScanner",
    "SecurityThreat",
    "SecurityEvent",
    "ThreatLevel",
    "ThreatCategory",
    "get_security_scanner",
    # Optimization and scaling components
    "PerformanceOptimizer",
    "PerformanceCache",
    "ConcurrentExecutor",
    "AdaptiveResourceManager",
    "PerformanceMetrics",
    "get_performance_optimizer",
    "AutoScaler",
    "LoadBalancer",
    "WorkloadAnalyzer",
    "ScalingMetrics",
    "ScalingDecision",
    "ScalingPolicy",
    "WorkloadPattern",
    "get_auto_scaler",
    # Global-first features
    "LocalizationManager",
    "SupportedLocales",
    "LocaleInfo",
    "get_localization_manager",
    "set_global_locale",
    "t",
    "format_localized_datetime",
    "format_localized_currency",
    "ComplianceEngine",
    "ComplianceFramework",
    "DataClassification",
    "ProcessingPurpose",
    "RetentionPeriod",
    "DataProcessingRecord",
    "PrivacyControlsManager",
    "get_compliance_engine",
    "log_data_processing",
    "check_data_compliance",
    "MultiRegionManager",
    "Region",
    "RegionConfig",
    "DataResidencyRequirement",
    "ReplicationStrategy",
    "DataLocation",
    "get_multi_region_manager",
    "store_data_globally",
    "get_optimal_region"
]
